[versions]
agp = "8.7.2"
kotlin = "1.9.24"
coreKtx = "1.13.1"
junit = "4.13.2"
junitVersion = "1.2.1"
espressoCore = "3.6.1"
appcompat = "1.7.0"
material = "1.12.0"
activity = "1.9.3"
constraintlayout = "2.2.0"
splashVersion = "1.2.0-alpha02"
lifecycle_version = "2.8.7"
room_version = "2.6.1"
coroutine_version = "1.9.0-RC"
billing_version = "6.0.1"
gson_version = "2.11.0"
event-bus-version = "3.2.0"
ksp = "2.0.21-1.0.25"

[libraries]
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
androidx-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }
androidx-espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }
androidx-appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }
androidx-activity = { group = "androidx.activity", name = "activity", version.ref = "activity" }
androidx-constraintlayout = { group = "androidx.constraintlayout", name = "constraintlayout", version.ref = "constraintlayout" }
splashscreen-dependency = {group = "androidx.core", name = "core-splashscreen", version.ref = "splashVersion"}
livedata = {group = "androidx.lifecycle", name = "lifecycle-livedata-ktx", version.ref = "lifecycle_version"}
viewmodel = {group = "androidx.lifecycle", name = "lifecycle-viewmodel-ktx", version.ref = "lifecycle_version"}
viewmodel-savedstate = {group = "androidx.lifecycle", name = "lifecycle-viewmodel-savedstate", version.ref = "lifecycle_version"}
gson-dependency = {group = "com.google.code.gson", name = "gson", version.ref = "gson_version"}
room-runtime = {group = "androidx.room", name = "room-runtime", version.ref = "room_version"}
room-compiller-processor = {group = "androidx.room", name = "room-compiler", version.ref = "room_version"}
room-coroutine-support-dependency = {group = "androidx.room", name = "room-ktx", version.ref = "room_version"}
#room-ksp = {group = "androidx.room", name = "room-compiler", version.ref = "room_version"}
coroutine-core = {group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-core", version.ref = "coroutine_version"}
coroutine-android = {group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-android", version.ref = "coroutine_version"}
event-bus = {group = "org.greenrobot", name = "eventbus", version.ref = "event-bus-version"}
billingclient = {group = "com.android.billingclient", name = "billing-ktx", version.ref = "billing_version"}



[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
room-ksp= {id = "com.google.devtools.ksp", version.ref = "ksp"}

